version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - restaurant

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - restaurant

  mysql:
    image: mysql:8
    container_name: restaurant_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: restaurantErp
      MYSQL_DATABASE: restaurantErp
      MYSQL_PASSWORD: restaurantErp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - restaurant

networks:
  restaurant:

volumes:
  mysql_data:
